name: haifora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar:
    path: ./curved_navigation_bar
  # UI & Fonts
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  # existing deps...
  provider: ^6.1.2
  shared_preferences: ^2.2.15

  # Firebase
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section like this:
  # assets:
  #   - images/
