// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfGxwM8RUo1-F-vSJz9yL5KfKtnlnR66g',
    appId: '1:153876333847:web:73a873e379ab6db3516352',
    messagingSenderId: '153876333847',
    projectId: 'haiforaapp-f3821',
    authDomain: 'haiforaapp-f3821.firebaseapp.com',
    storageBucket: 'haiforaapp-f3821.firebasestorage.app',
    measurementId: 'G-ZFL7J6N8YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4syJPJcJeOLtXc7_BB6nJC_rmpY-db20',
    appId: '1:153876333847:android:6e177268e1ed5a7b516352',
    messagingSenderId: '153876333847',
    projectId: 'haiforaapp-f3821',
    storageBucket: 'haiforaapp-f3821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2qiXXrr9gBlwRrVlJYV52CHT6pi0x3A',
    appId: '1:153876333847:ios:b7687806f64a7776516352',
    messagingSenderId: '153876333847',
    projectId: 'haiforaapp-f3821',
    storageBucket: 'haiforaapp-f3821.firebasestorage.app',
    iosBundleId: 'com.haifora.app.haifora',
  );
}
