// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOtSIcWc81leSKGHfq3da9fEqE36AKkM',
    appId: '1:397709827493:web:83409558d6f780058ddc4c',
    messagingSenderId: '397709827493',
    projectId: 'haifora-v2',
    authDomain: 'haifora-v2.firebaseapp.com',
    storageBucket: 'haifora-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkhBhXmFbM3ymkeO2jamHL0pB6MoCaxVo',
    appId: '1:397709827493:android:68f99bff6826f6368ddc4c',
    messagingSenderId: '397709827493',
    projectId: 'haifora-v2',
    storageBucket: 'haifora-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0HeIzxEoQNmz5EqzaSPaNWPjKn2qNbZI',
    appId: '1:397709827493:ios:fe6b5e99811ba4928ddc4c',
    messagingSenderId: '397709827493',
    projectId: 'haifora-v2',
    storageBucket: 'haifora-v2.firebasestorage.app',
    iosBundleId: 'com.haifora.app.haifora',
  );

}