import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // ✅ Add this
import 'firebase_options.dart'; // ✅ Auto-generated by flutterfire configure

import 'theme.dart';
import 'signin_screen.dart';
import 'home_screen.dart';
import 'welcome_screen.dart';

void main() async {
WidgetsFlutterBinding.ensureInitialized(); // ✅ Needed before Firebase init
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform, // ✅ Use generated options
);
runApp(const MyApp());
}

class MyApp extends StatefulWidget {
const MyApp({super.key});

@override
State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
ThemeMode _themeMode = ThemeMode.light;

void _toggleTheme() {
setState(() {
_themeMode =
_themeMode == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
});
}

@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Haifora',
theme: HaiforaTheme.lightTheme,
darkTheme: HaiforaTheme.darkTheme,
themeMode: _themeMode,
home: WelcomeScreen(
toggleTheme: _toggleTheme,
isDarkMode: _themeMode == ThemeMode.dark,
),
);
}
}

